Mutex.cxx: fix invalid stack access in DEBUG_MUTEX case
gcc major version 12 issues the following warning:

```
common/Mutex.cxx: In constructor ‘xwmfs::Mutex::Mutex()’:
common/Mutex.cxx:48:71: error: dangling pointer ‘attr’ to ‘debug_attr’ may be used [-Werror=dangling-pointer=]
   48 |                 const int attr_destr_res = ::pthread_mutexattr_destroy(
      |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
   49 |                         attr
      |                         ~~~~
   50 |                 );
      |                 ~
common/Mutex.cxx:18:39: note: ‘debug_attr’ declared here
   18 |                 ::pthread_mutexattr_t debug_attr;
      |                                       ^~~~~~~~~~
common/Mutex.cxx:39:33: error: using dangling pointer ‘attr’ to ‘debug_attr’ [-Werror=dangling-pointer=]
   39 |         if( ::pthread_mutex_init(&m_pmutex, attr) != 0 )
      |             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
common/Mutex.cxx:18:39: note: ‘debug_attr’ declared here
   18 |                 ::pthread_mutexattr_t debug_attr;
      |                                       ^~~~~~~~~~
```

and indeed the `pthread_mutexattr_destroy` references the already
out-of-scope `debug_attr`. It looks like this didn't show any symptoms
up to now, since no new variables are put onto the stack at this time.

To make things proper use a globally initialized attribute object
instead. Cleanup is a bit hairy, use atexit() for now to clean it up. In
fuse context cleanup is a bit hairy anyway.

Also see Gentoo bug:

https://bugs.gentoo.org/841020