SystemException: use XSI compliant version of strerror_r
To support building against non GNU libc variants use the XSI compliant
version of strerror_r. This is harder than is sounds since there is a
mess of preprocessor defines involved.